name: "compute toml_sha"
description: "computes the SHA of the pyproject.toml file"
outputs:
  pyproject_toml_sha:
    description: "SHA of pyproject.toml file"
    value: ${{steps.pyproject_toml_sha.outputs.PYPROJECT_TOML_SHA}}
inputs:
  pyproject_toml_path:
    description: "The path to the pyproject.toml file"
    required: true

runs:
  using: composite

  steps:
    - name: Calculate pyproject.toml SHA
      id: pyproject_toml_sha
      run: |
        set -o pipefail
        PYPROJECT_TOML_SHA=$(sha256sum ${{ inputs.pyproject_toml_path }} | cut -f1 -d" ")
        echo "PYPROJECT_TOML_SHA=$PYPROJECT_TOML_SHA" >> "$GITHUB_OUTPUT"
        echo "$PYPROJECT_TOML_SHA"
      shell: bash
