name: docker build and push
on: 
  pull_request:
    paths:
      - 'pyhelloworld/pyproject.toml'
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        run: cd pyhelloworld && docker build .

 