on:
    workflow_call:
jobs:
    callee:
        runs-on: ubuntu-latest
        steps:
            - name: Wait for Other Workflows
              uses: lewagon/wait-on-check-action@v1.4.1
              with:
                  ref: ${{ github.ref }}
                  running-workflow-name: "caller / callee"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  wait-interval: 10
