name: docker build and push
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v5
      -
        id: pyproject_toml_sha
        run: |
          set -o pipefail
          PYPROJECTTOMLSHA=$(sha256sum pyhelloworld/pyproject.toml | cut -f1 -d" ")
          echo "PYPROJECTTOMLSHA=$PYPROJECTTOMLSHA" >> "$GITHUB_ENV"
      - 
        run:
          echo $PYPROJECTTOMLSHA
      