name: docker build and push
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          export FOO=bar
          echo "::set-env name=FOO::$FOO"
      - run: echo $FOO

      