name: docker build and push
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
      - name: regctl login to quay.io
        uses: regclient/actions/regctl-login@main
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Calculate pyproject.toml SHA
        id: pyproject_toml_sha
        run: |
          set -o pipefail
          PYPROJECT_TOML_SHA=$(sha256sum pyhelloworld/pyproject.toml | cut -f1 -d" ")
          echo "PYPROJECT_TOML_SHA=$PYPROJECT_TOML_SHA" >> "$GITHUB_OUTPUT"

      - id: lowercase_tags
        uses: ASzc/change-string-case-action@v6
        with:
          string: quay.io/${{ vars.QUAY_ORG }}/${{github.event.repository.name}}:${{steps.pyproject_toml_sha.outputs.PYPROJECT_TOML_SHA}}
      - name: tag exists
        run: |
          regctl tag ls ${{ steps.lowercase_tags.outputs.lowercase }}
          
            


      # - name: Login to quay.io
      #   uses: docker/login-action@v3
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USER }}
      #     password: ${{ secrets.QUAY_PASSWORD }}
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     platforms: linux/amd64
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: "{{defaultContext}}:pyhelloworld"
      #     push: true
      #     tags: ${{ steps.lowercase_tags.outputs.lowercase }}
