name: docker build and push
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: echo tag
        run: echo "quay.io/${{ vars.QUAY_ORG }}/${{github.repository}}:${{github.sha}}"
