name: docker build and push
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login
        env:
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
        run: echo "$quay_password" > docker login quay.io -u --password-stdin
      - name: Build docker image
        run: cd pyhelloworld && docker build .
 