name: docker build and push
on: push
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: echo tag
        run: echo "quay.io/${{ secrets.QUAY_ORG }}/${{github.repository}}ci:${{github.sha}}"
